// Code generated by MockGen. DO NOT EDIT.
// Source: ./conn_manager_factory.go

// Package mockmq is a generated GoMock package.
package mockmq

import (
	reflect "reflect"

	mq "github.com/RoyceAzure/rj/infra/mq"
	gomock "github.com/golang/mock/gomock"
)

// MockMQConnManagerFactory is a mock of MQConnManagerFactory interface.
type MockMQConnManagerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockMQConnManagerFactoryMockRecorder
}

// MockMQConnManagerFactoryMockRecorder is the mock recorder for MockMQConnManagerFactory.
type MockMQConnManagerFactoryMockRecorder struct {
	mock *MockMQConnManagerFactory
}

// NewMockMQConnManagerFactory creates a new mock instance.
func NewMockMQConnManagerFactory(ctrl *gomock.Controller) *MockMQConnManagerFactory {
	mock := &MockMQConnManagerFactory{ctrl: ctrl}
	mock.recorder = &MockMQConnManagerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMQConnManagerFactory) EXPECT() *MockMQConnManagerFactoryMockRecorder {
	return m.recorder
}

// GetManager mocks base method.
func (m *MockMQConnManagerFactory) GetManager() (mq.IMQConnManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManager")
	ret0, _ := ret[0].(mq.IMQConnManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManager indicates an expected call of GetManager.
func (mr *MockMQConnManagerFactoryMockRecorder) GetManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManager", reflect.TypeOf((*MockMQConnManagerFactory)(nil).GetManager))
}

// Init mocks base method.
func (m *MockMQConnManagerFactory) Init(params mq.MQConnParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockMQConnManagerFactoryMockRecorder) Init(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockMQConnManagerFactory)(nil).Init), params)
}
