// Code generated by MockGen. DO NOT EDIT.
// Source: ./jkafka_writer.go

// Package mockjkafka is a generated GoMock package.
package mockjkafka

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	kafka_go "github.com/segmentio/kafka-go"
)

// MockKafkaWriter is a mock of KafkaWriter interface.
type MockKafkaWriter struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaWriterMockRecorder
}

// MockKafkaWriterMockRecorder is the mock recorder for MockKafkaWriter.
type MockKafkaWriterMockRecorder struct {
	mock *MockKafkaWriter
}

// NewMockKafkaWriter creates a new mock instance.
func NewMockKafkaWriter(ctrl *gomock.Controller) *MockKafkaWriter {
	mock := &MockKafkaWriter{ctrl: ctrl}
	mock.recorder = &MockKafkaWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaWriter) EXPECT() *MockKafkaWriterMockRecorder {
	return m.recorder
}

// WriteMessages mocks base method.
func (m *MockKafkaWriter) WriteMessages(arg0 context.Context, arg1 []kafka_go.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMessages", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages.
func (mr *MockKafkaWriterMockRecorder) WriteMessages(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockKafkaWriter)(nil).WriteMessages), arg0, arg1)
}
