#build stage
FROM golang:1.23-alpine3.21 AS builder
WORKDIR /app
COPY . .
RUN go build -o main server/cmd/main.go

#Run stage
FROM golang:1.23-alpine3.21
WORKDIR /app
COPY --from=builder /app/main .
COPY .env .
COPY go.mod .

ENV SERVICEID=logger
ENV LOCAL_LOG_FILE_DIR=./temp
CMD [ "/app/main" ]